# Practical Day2

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])

In [2]:
print(x)

[1 2 3 4 5]


In [4]:
m = np.array([[1,5,2],
            [4,7,4],
            [2,0,9]])

In [5]:
print(m)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [9]:
print('Matrix Transpose:\n',m.transpose())

Matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]]


In [10]:
print('Matrix Determinant',np.linalg.det(m)) #linear algebra determinant

Matrix Determinant -105.00000000000006


In [13]:
m_inv = np.linalg.inv(m)
print('Matrix inverse\n',m_inv)

Matrix inverse
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]]


In [20]:
iden_m = np.dot(m,m_inv)
print('Identical of matrix\n',iden_m)

Identical of matrix
 [[ 1.00000000e+00 -8.32667268e-17  5.55111512e-17]
 [ 1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 2.77555756e-17 -1.38777878e-17  1.00000000e+00]]


In [16]:
iden_m_r = np.round(np.abs(iden_m),0)

In [19]:
print('Round the values of matrix\n',iden_m_r)

Round the values of product matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
eigen_vals,eigen_vecs  = np.linalg.eig(m)
print('Eigen values\n', eigen_vals,'\n')
print('Eigen vectors\n',eigen_vecs)

Eigen values
 [-1.32455532 11.32455532  7.        ] 

Eigen vectors
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]]


In [25]:
U,S,VT = np.linalg.svd(m)      #Singular Value Decomposision
print('getting SVD outputs: \n')
print('U\n',U,'\n')
print('S\n',S,'\n')
print('VT\n',VT)

getting SVD outputs: 

U
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S
 [12.10668383  6.91783499  1.25370079] 

VT
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]]


In [29]:
zeros_array = np.zeros((2,3)) 
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [67]:
#Descriptive Statistic
import scipy as sp
import numpy as np


In [68]:
#get data
nums  = np.random.randint(1,20,size = (1,15))[0]
print('Data : ',nums)

Data :  [ 2  9  2 13  9 10 13  8  2  2  2  9  3  8  4]


In [69]:
#get descriptive stats
import statistics as s
print('Mean :',np.mean(nums))
print('Median :',np.median(nums))
print('Mode :',s.mode(nums))
print('Standerd deviation :',np.std(nums))
print('Variance :',np.var(nums))
print('Skew :',sp.stats.skew(nums))
print('Kurtosis :', sp.stats.kurtosis(nums))

Mean : 6.4
Median : 8.0
Mode : 2
Standerd deviation : 3.9966652766191633
Variance : 15.973333333333334
Skew : 0.21253110631769018
Kurtosis : -1.3920487958506247


In [66]:
from scipy.stats import skew
import numpy as np

# Example data
data = [2, 8, 0, 4, 1, 9, 6, 3, 5, 7]

# Calculate skewness
skewness = skew(data)

print(f"Skewness of the data: {skewness}")


Skewness of the data: 0.0


In [72]:
import scipy
print(scipy.__version__)

1.9.1


In [2]:
#write a code to generate 3 random int between 100 - 999 which is divisible by 5
import random

numbers = random.sample(range(100, 1000, 5), 3)
print("Random numbers divisible by 5:", numbers)

Random numbers divisible by 5: [825, 905, 720]


In [4]:
#write a code to generate 100 random lottery tickets and pick 2 lucky from it,
#10 dig lottery number
#100 ticket number must be unique
import random

# Generate 100 unique 10-digit lottery tickets
tickets = set()
while len(tickets) < 100:
    ticket = random.randint(10**9, 10**10 - 1)  # ensures 10-digit number
    tickets.add(ticket)

tickets = list(tickets)  # convert set to list

# Pick 2 lucky tickets
lucky_tickets = random.sample(tickets, 2)

print("100 Unique Lottery Tickets:")
for i, t in enumerate(tickets, 1):
    print(f"Ticket {i}: {t}")

print("\nLucky Tickets:", lucky_tickets)


100 Unique Lottery Tickets:
Ticket 1: 3350059008
Ticket 2: 3875672074
Ticket 3: 3343410710
Ticket 4: 8965163545
Ticket 5: 5491171867
Ticket 6: 6524796959
Ticket 7: 9157598252
Ticket 8: 7904082989
Ticket 9: 4428524081
Ticket 10: 3071358520
Ticket 11: 6068194364
Ticket 12: 4886664789
Ticket 13: 8367651416
Ticket 14: 2673681501
Ticket 15: 2699855975
Ticket 16: 4607753328
Ticket 17: 6670341234
Ticket 18: 6948311667
Ticket 19: 7820925046
Ticket 20: 7368763514
Ticket 21: 9533325951
Ticket 22: 3268924038
Ticket 23: 1744959113
Ticket 24: 9357801100
Ticket 25: 6834924695
Ticket 26: 7779921570
Ticket 27: 6214746276
Ticket 28: 1350494374
Ticket 29: 3556703913
Ticket 30: 9254035115
Ticket 31: 3935199403
Ticket 32: 7128148141
Ticket 33: 9266753709
Ticket 34: 9856689329
Ticket 35: 9756321975
Ticket 36: 7624590537
Ticket 37: 8225224403
Ticket 38: 8389390049
Ticket 39: 8797620458
Ticket 40: 5668609770
Ticket 41: 6241794796
Ticket 42: 9160388332
Ticket 43: 6214618866
Ticket 44: 2975678196
Ticket 45: 78

In [6]:
#Generate random password, meet folowing conditions

#pwd len = 10
#it contain 2 upper case letter , 1 dig , 1 special symbol
import random
import string

def generate_password():
    # Required components
    uppercase = random.sample(string.ascii_uppercase, 2)   # 2 uppercase letters
    digit = random.choice(string.digits)                   # 1 digit
    symbol = random.choice("!@#$%^&*()_+-=[]{}|;:,.<>?/")  # 1 special symbol

    # Remaining characters (10 - 4 = 6 chars left, can be lowercase/anything)
    remaining = random.choices(string.ascii_lowercase + string.digits, k=6)

    # Combine all parts
    password_list = uppercase + [digit] + [symbol] + remaining
    random.shuffle(password_list)  # Shuffle to avoid predictable order

    return "".join(password_list)

# Generate and print password
print("Generated Password:", generate_password())


Generated Password: 8vT2j]3b3Y
